version: "3"
services:
  docs:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/docs
    stdin_open: true # Keep STDIN open even if not attached
    tty: true # Allocate a pseudo-tty
