site_name: Productivity
site_url: https://productivity.netguru.com

# Theme
theme:
  name: material
  language: en
  icon:
    logo: material/trending-up
  palette:
    primary: green
    accent: deep orange

# Repository
repo_name: netguru/productivity
repo_url: https://github.com/netguru/productivity

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
