version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: mkdocs build --clean
      - persist_to_workspace:
          root: ~/project
          paths:
            - site

  deploy:
    executor: python/default
    steps:
      - attach_workspace:
          at: ~/project
      - run: pip install awscli
      # Sync and delete any old files from the S3 bucket.
      - run: aws s3 sync site/ s3://$AWS_S3_BUCKET --acl public-read --cache-control "max-age=86400" --exclude "*.py*" --delete
      # Allow `awscli` to make requests to CloudFront.
      - run: aws configure set preview.cloudfront true
      # Invalidate every object.
      - run: aws cloudfront create-invalidation --distribution-id $AWS_CF_DISTRIBUTION_ID --paths "/*"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
